<div class="footer">
    <div class="links">
Powered by<br>
<img class="v-middle" width="70" src="https://s3-eu-west-1.amazonaws.com/chippin-assets/chippin.png" alt="Chippin">
    </div>
    <div class="links">
Secured by<br>
<img class="v-middle" width="70" src="https://s3-eu-west-1.amazonaws.com/chippin-assets/stripe.png" alt="Stripe">
    </div>
    <div class="form-alt"><?php echo $this->getRedirectMessage() ?></div>
</div>
