web:
  build: .
  ports:
    - "80:80"
  links:
    - mysql
  env_file:
    - env
  volumes:
    - .:/var/chippin
    - ./src/var/connect:/var/www/htdocs/var/connect

mysql:
  image: mysql:5.6.23
  env_file:
    - env

#selenium:
  #image: selenium/standalone-chrome
  #ports:
    #- "4444:4444"
