<?php
    if ($this->getSignupLink()):
?>
<div class="chippin-payment-notice">
    <?php echo Mage::helper('chippinpayment')->__('Not yet got a Chippin account? Click <a href="%s" target="_blank">here</a> to register.', $this->getSignupLink()); ?>
</div>
<?php
    endif;
?>
<ul>
    <li class="chippin-footer">
        <div class="chippin-footer-inner">
            <div class="chippin-footer-badge">
              Powered by<br>
              <img class="chippin-logo" width="88" src="https://s3-eu-west-1.amazonaws.com/chippin-assets/chippin.png" alt="Chippin">
            </div>
            <div class="chippin-footer-badge">
                Secured by<br>
                <img class="chippin-logo" width="88" src="https://s3-eu-west-1.amazonaws.com/chippin-assets/stripe.png" alt="Stripe">
            </div>
        </div>
    </li>
    <li>
        <?php echo $this->getHrefChippinCancel() ?>
    </li>
    <li>
        <?php echo $this->getHrefChippinComplete() ?>
    </li>
    <li>
        <?php echo $this->getHrefChippinContribute() ?>
    </li>
    <li>
        <?php echo $this->getHrefChippinFail() ?>
    </li>
    <li>
        <?php echo $this->getHrefChippinInvite() ?>
    </li>
    <li>
        <?php echo $this->getHrefChippinRejecte() ?>
    </li>
    <li>
        <?php echo $this->getHrefChippinTimeout() ?>
    </li>
</ul>
